name: News to Bluesky Bot

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser pyyaml

      - name: Download processed URLs
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: processed-urls
          path: .

      - name: Run bot
        run: python main.py

      - name: Debug processed file
        run: |
          echo "PWD:"
          pwd
          echo "Files:"
          ls -l
          echo "processed_urls.json:"
          cat processed_urls.json || echo "processed_urls.json not found"


      - name: Upload processed URLs
        uses: actions/upload-artifact@v4
        with:
          name: processed-urls
          path: processed_urls.json
